### ISSUE TITLE
Errors with distributed training on a single node

### ISSUE THREAD

**Issue by roudimit** [facebookresearch/av_hubert#102]
Hi, thanks for the great work! I am trying to fine-tune the model for audio-visual speech recognition using multiple GPUs on a single node. I am running into consistent problems when using multiple GPUs, but fine-tuning with a single GPU works fine. In all cases, I adjust `distributed_world_size`, `nprocs_per_node`, and `update_freq` accordingly.

I use slurm like `sbatch train.sh`, and `train.sh` contains: 
```
srun fairseq-hydra-train \
    --config-dir ${AV_HUBERT}/conf/finetune \
    ...
```

Here is the first error. When it happens, the process on one GPU will die while the processes on the other GPU(s) will keep running (the training effectively stops). I tried to run it with HYDRA_FULL_ERROR=1, but I found that the processes on each GPU seem to double which causes a CUDA out of memory error (no issues with the memory when this flag is not enabled).

```
Traceback (most recent call last):
  File "/usr/users/roudi/vtenvs/anaconda3/envs/muavic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/users/roudi/vtenvs/anaconda3/envs/muavic/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main
    _hydra_main(cfg)
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 56, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/distributed/utils.py", line 354, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq_cli/train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/usr/users/roudi/vtenvs/anaconda3/envs/muavic/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq_cli/train.py", line 301, in train
    for i, samples in enumerate(progress):
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/logging/progress_bar.py", line 191, in __iter__
    for i, obj in enumerate(self.iterable, start=self.n):
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/data/iterators.py", line 56, in __next__
    x = next(self._itr)
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/data/iterators.py", line 557, in _chunk_iterator
    for x in itr:
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/data/iterators.py", line 56, in __next__
    x = next(self._itr)
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/data/iterators.py", line 690, in __next__
    raise item
  File "/usr/users/roudi/muavic/av_hubert/fairseq/fairseq/data/iterators.py", line 620, in run
    for item in self._source:
  File "/usr/users/roudi/vtenvs/anaconda3/envs/muavic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/users/roudi/vtenvs/anaconda3/envs/muavic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/usr/users/roudi/vtenvs/anaconda3/envs/muavic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/usr/users/roudi/vtenvs/anaconda3/envs/muavic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 526141) exited unexpectedly

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Here is the second error. It happens when the steps for `freeze_finetune_updates` is reached and the encoder becomes trainable. This error causes the training to crash:
```
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/autograd/__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 5, 7, 7], strides() = [245, 1, 49, 7, 1]
bucket_view.sizes() = [64, 1, 5, 7, 7], strides() = [245, 245, 49, 7, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:323.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1344: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1334: UserWarning: Using a non-full backward hook when outputs are generated by different autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when outputs are generated by different autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1309: UserWarning: Using non-full backward hooks on a Module that does not return a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not return a "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/autograd/__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 5, 7, 7], strides() = [245, 1, 49, 7, 1]
bucket_view.sizes() = [64, 1, 5, 7, 7], strides() = [245, 245, 49, 7, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:323.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1344: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1334: UserWarning: Using a non-full backward hook when outputs are generated by different autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when outputs are generated by different autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1309: UserWarning: Using non-full backward hooks on a Module that does not return a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not return a "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/autograd/__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 5, 7, 7], strides() = [245, 1, 49, 7, 1]
bucket_view.sizes() = [64, 1, 5, 7, 7], strides() = [245, 245, 49, 7, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:323.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1344: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1334: UserWarning: Using a non-full backward hook when outputs are generated by different autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when outputs are generated by different autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1309: UserWarning: Using non-full backward hooks on a Module that does not return a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not return a "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/autograd/__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 5, 7, 7], strides() = [245, 1, 49, 7, 1]
bucket_view.sizes() = [64, 1, 5, 7, 7], strides() = [245, 245, 49, 7, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:323.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1344: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1334: UserWarning: Using a non-full backward hook when outputs are generated by different autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when outputs are generated by different autograd Nodes "
/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py:1309: UserWarning: Using non-full backward hooks on a Module that does not return a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not return a "
Traceback (most recent call last):
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/bin/fairseq-hydra-train", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/users/roudi/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/hydra/core/utils.py", line 129, in run_job
    ret.return_value = task_function(task_cfg)
  File "/usr/users/roudi/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/usr/users/roudi/av_hubert/fairseq/fairseq/distributed/utils.py", line 344, in call_main
    torch.multiprocessing.spawn(
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/usr/users/roudi/av_hubert/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/usr/users/roudi/av_hubert/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/users/roudi/av_hubert/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/users/roudi/av_hubert/fairseq/fairseq/trainer.py", line 812, in train_step
    self._check_grad_norms(grad_norm)
  File "/usr/users/roudi/av_hubert/fairseq/fairseq/trainer.py", line 1328, in _check_grad_norms
    raise FloatingPointError(
FloatingPointError: Fatal error: gradients are inconsistent between workers. Try --ddp-backend=legacy_ddp. Or are you mixing up different generation of GPUs in training?
--------------------------------------------------------------------------------
grad_norm across the workers:
rank   0 = 13.87355754
rank   1 = 13.87527466
rank   2 = 13.96525167
rank   3 = 13.87173055

--------------------------------------------------------------------------------

/usr/users/roudi/vtenvs/anaconda3/envs/avhubert/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 24 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Do you have any suggestions to fix these problems? I appreciate the help, thanks!

**Comment by roudimit** [comment]
I was able to solve the 2nd problem (`Fatal error: gradients are inconsistent between workers`) with the recommendation in the error: `--ddp-backend=legacy_ddp`. However, the first problem still persists (Dataloader exits unexpectedly).
